# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b01465f016a1d30111243f8e06f958ed221850082b6563f7a921a97a80e0eef0eed0f61f1c33331f18b10342131bf68225a7ce38c3ce37d4166388431a6b3291

test:
  secret_key_base: f28d222d55a87880ec40a3d23766cb79373f98743cd7b280242d804a753f9c43ea547e43d908ebe46a8088b3e0d9b39c4eb43295a09d2def3b756c4eb217a2db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
